# Generated by Django 2.0.5 on 2018-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Chris', max_length=50),
        ),
    ]
